spring:
  profiles:
    active: dev

management:
  # Endpoint'lerin temel yolu
  endpoints:
    web:
      base-path: /actuator
      # Temel endpoint'ler - tüm ortamlarda gerekli olanlar
      exposure:
        include: health,info

  # Health endpoint'i temel yapılandırması
  endpoint:
    health:
      # Bu ayar profile'lara göre değişebilir
      show-details: never
      show-components: never

  # Info endpoint'i yapılandırması
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Uygulama bilgileri - tüm ortamlarda aynı
info:
  app:
    name: Library Management System
    description: Patika.dev & Getir Java Spring Boot Bootcamp - Final Project
    version: 1.0.0
    developer: eaaslan