spring:
  profiles:
    active: dev

management:

  endpoints:
    web:
      base-path: /actuator

      exposure:
        include: health,info

  endpoint:
    health:

      show-details: never
      show-components: never


  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  app:
    name: Library Management System
    description: Patika.dev & Getir Java Spring Boot Bootcamp - Final Project
    version: 1.0.0
    developer: eaaslan

app:
  library:
    name: ${LIBRARY_NAME:Library Management System}

  company:
    name: ${COMPANY_NAME:GETIR Java Spring Boot Bootcamp}

  pdf:
    export:

      max-records: ${PDF_MAX_RECORDS:10000}

      cache-enabled: ${PDF_CACHE_ENABLED:true}
      cache-duration: ${PDF_CACHE_DURATION:PT10M}

      async-enabled: ${PDF_ASYNC_ENABLED:false}
      thread-pool-size: ${PDF_THREAD_POOL_SIZE:2}

logging:
  level:
    tr.com.eaaslan.library.service.BorrowingPdfExportService: DEBUG
    tr.com.eaaslan.library.controller.BorrowingPdfExportController: DEBUG