spring:
  jwt:
    secret: 4261656C64756E6732303235536563726574546F6B656E4B6579466F724C6962726172794170706C69636174696F6E
    expiration-ms: 86400000
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,env,configprops,loggers,beans,threaddump,heapdump
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

info:
  environment: development
  debug: true
  database-url: ${spring.datasource.url}